//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uygulama1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_comment
    {
        public string film_name { get; set; }
        public string comment { get; set; }
        public string user_name { get; set; }
        public int user_id { get; set; }
        public Nullable<int> film_id { get; set; }
    
        public virtual film_list film_list { get; set; }
        public virtual user_profile user_profile { get; set; }
    }
}
